# Generated by Django 3.1.3 on 2021-02-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.TextField(blank=True)),
                ('RERA', models.CharField(blank=True, max_length=3)),
                ('Society', models.CharField(blank=True, max_length=20)),
                ('Developer', models.CharField(blank=True, max_length=50)),
                ('Completion', models.CharField(blank=True, max_length=5)),
                ('Age', models.CharField(blank=True, max_length=10)),
                ('Ratings', models.CharField(blank=True, max_length=10)),
                ('Contact', models.CharField(blank=True, max_length=10)),
                ('Sub_Locality', models.CharField(blank=True, max_length=50)),
                ('Locality', models.CharField(blank=True, max_length=20)),
                ('Google_Pin', models.TextField(blank=True)),
                ('Society_Configuration_1', models.CharField(blank=True, max_length=100)),
                ('Society_Configuration_2', models.CharField(blank=True, max_length=100)),
                ('Price', models.CharField(blank=True, max_length=12)),
                ('Promoters_Members', models.TextField(blank=True)),
                ('Land_Owner_and_Investor_Details', models.TextField(blank=True)),
            ],
        ),
    ]
