# Generated by Django 3.1.3 on 2021-02-26 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Filter_Name', models.CharField(max_length=10, null=True)),
                ('Filter_Id', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FilterType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Filter_Type_Name', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.TextField(blank=True, null=True)),
                ('RERA', models.CharField(blank=True, max_length=3, null=True)),
                ('Society', models.CharField(blank=True, max_length=20, null=True)),
                ('Developer', models.CharField(blank=True, max_length=50, null=True)),
                ('Completion', models.CharField(blank=True, max_length=5, null=True)),
                ('Age', models.CharField(blank=True, max_length=10, null=True)),
                ('Ratings', models.CharField(blank=True, max_length=10, null=True)),
                ('Contact', models.CharField(blank=True, max_length=10, null=True)),
                ('Sub_Locality', models.CharField(blank=True, max_length=50, null=True)),
                ('Locality', models.CharField(blank=True, max_length=20, null=True)),
                ('Google_Pin', models.TextField(blank=True, null=True)),
                ('Society_Configuration_1', models.CharField(blank=True, max_length=100, null=True)),
                ('Society_Configuration_2', models.CharField(blank=True, max_length=100, null=True)),
                ('Price', models.CharField(blank=True, max_length=12, null=True)),
                ('Promoters_Members', models.TextField(blank=True, null=True)),
                ('Land_Owner_and_Investor_Details', models.TextField(blank=True, null=True)),
                ('Filters', models.ManyToManyField(to='main.Filter')),
            ],
        ),
        migrations.AddField(
            model_name='filter',
            name='Filter_Type_Name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.filtertype'),
        ),
    ]
